
import time
import random
import google.generativeai as genai
import PIL.Image

class Agent:
    def __init__(self, model_name: str, name: str, temperature: float, sleep_time: float=1) -> None:

        self.model_name = model_name
        self.name = name
        self.temperature = temperature
        self.memory_lst = ""
        self.sleep_time = sleep_time


    def query(self, prompt: str, api_key: str, image_file: str) -> str:

        time.sleep(1)

        genai.configure(api_key=api_key, transport='rest')  # 填入自己的api_key
        model = genai.GenerativeModel(model_name="gemini-pro-vision")
        img = PIL.Image.open(image_file)
        ff = False
        step = 0
        while ff == False or step < 5:
            try:
                response = model.generate_content([prompt, img])
                response.resolve()
                ff = True
                break
            except:
                time.sleep(1)
                step += 1
        if ff == True:
            try:
                return response.text
            except:
                return "error"
        else:
            return "error"

    def set_meta_prompt(self, meta_prompt: str):
        """Set the meta_prompt

        Args:
            meta_prompt (str): the meta prompt
        """
        self.memory_lst = self.memory_lst + '\n' + meta_prompt

    def add_event(self, event: str):
        """Add an new event in the memory

        Args:
            event (str): string that describe the event.
        """
        self.memory_lst = self.memory_lst + '\n' + event

    def add_memory(self, memory: str):
        """Monologue in the memory

        Args:
            memory (str): string that generated by the model in the last round.
        """
        self.memory_lst = self.memory_lst + '\n' + memory
        print(f"----- {self.name} -----\n{memory}\n")

    def ask(self, image_file: str):
        """Query for answer

        Args:
        """
        # query

        return self.query(self.memory_lst, api_key=self.google_api_key, image_file = image_file)

